[tools]
aws-cli = "latest"
python = "3.12.11"
uv = "0.8.22"

[vars]
# 共通変数定義
project_name = "test-pj"

[tasks.deploy-cfn-dev-database]
description = "CloudformationでDEV環境のdatabaseパートをデプロイします。"
usage = '''
arg "envname" "環境名" default="dev"
'''
run = '''
aws cloudformation deploy \
    --stack-name {{vars.project_name}}-{{arg(name="envname")}}-database \
    --template-file infrastructure/database.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides \
        ProjectName={{vars.project_name}} \
        Environment={{arg(name="envname")}}
'''

[tasks.deploy-cfn-dev-backend]
description = "CloudformationでDEV環境のbackednパートをデプロイします。"
usage = '''
arg "envname" "環境名" default="dev"
'''
run = '''
aws cloudformation deploy \
    --stack-name {{vars.project_name}}-{{arg(name="envname")}}-backend \
    --template-file infrastructure/backend.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides \
        ProjectName={{vars.project_name}} \
        EnvName={{arg(name="envname")}}
'''

[tasks.deploy-cfn-dev-sample-frontend]
description = "CloudformationでDEV環境のsample-frontendパートをデプロイします。"
usage = '''
arg "envname" "環境名" default="dev"
arg "part" "パート名（変更不可）" default="sample-frontend"
'''
run = '''
aws cloudformation deploy \
    --stack-name {{vars.project_name}}-{{arg(name="envname")}}-{{arg(name="part")}} \
    --template-file infrastructure/sample-frontend.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides \
        ProjectName={{vars.project_name}} \
        Environment={{arg(name="envname")}}
'''

[tasks.delete-cfn-dev-sample-frontend]
description = "CloudformationでDEV環境のsample-frontendパートを削除します。"
usage = '''
arg "envname" "環境名" default="dev"
arg "part" "パート名（変更不可）" default="sample-frontend"
'''
run = '''
aws cloudformation delete-stack \
    --stack-name {{vars.project_name}}-{{arg(name="envname")}}-{{arg(name="part")}}

aws cloudformation wait stack-delete-complete \
    --stack-name {{vars.project_name}}-{{arg(name="envname")}}-{{arg(name="part")}}
'''
